version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
          working_directory: GerenciadorDeJogos.Api
      - run:
          name: Build
          command: dotnet build -c Release
          working_directory: GerenciadorDeJogos.Api
      - run:
          name: Running Tests
          command: dotnet test
          working_directory: GerenciadorDeJogos/GerenciadorDeJogos.Test
